project:
  type: book

book:
  title: "nflbeginnR"
  author: "Sebastian Carl & Tan Ho"
  date: "4/09/2023"
  chapters:
    - 00_index.qmd
    - 01_get_started.qmd
    - 02_dataviz.qmd
    - 03_transform.qmd
    - 04_tidy.qmd
    - 05_import.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

