project:
  type: book

book:
  title: "nflbeginR"
  author: "Sebastian Carl & Tan Ho"
  date: "4/09/2023"
  chapters:
    - index.qmd
    - get_started.qmd
    - dataviz.qmd
    - transform.qmd
    - tidy.qmd
    - import.qmd
    - contribute.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

