---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# nflbeginR

The goal of nflbeginR is to provide NFL data exercises and case studies to supplement the excellent existing introductory resources for learning R.

## Existing Resources

nflbeginR is primarily based on: 

- readings from [R for Data Science](https://r4ds.had.co.nz) by Hadley Wickham and Garret Grolemund
- and/or lectures/slides from [Data Science in a Box](https://datasciencebox.org/) by Mine Cetinkaya-Rundel

Other great introductory resources are:

- [Introverse](https://spielmanlab.github.io/introverse/) by Stephanie Spielman
- [RStudio Cloud Primers](https://rstudio.cloud/learn/primers) by RStudio's education team
- [Modern Dive](https://moderndive.com/) for basic stats introductions
- [Introduction to Statistical Learning](https://www.statlearning.com/) for a more detailed introduction to statistics with R
- [DataQuest](https://dataquest.com) for more online R exercises

## Roadmap


## Next steps

- Shiny
- Reports and Automation
- Advanced R Programming
- Statistics and Modelling
- Scraping and APIs
- Data Viz
- Functions and Packages
